language: node_js
node_js:
- '8'
deploy:
  repo: pixelass/pixelass.github.io
  email: greg@pixelass.com
  name: Gregor Adams (via Travis CI)
  local-dir: public
  target-branch: master
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
script: echo build
